[package]
name = "leptos_animation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = "0.3.1"
instant = { version = "0.1.12", features = ["wasm-bindgen"] }
